# Travis's native R Image (http://docs.travis-ci.com/user/languages/r/)
language: r
sudo: required
cache: packages
warnings_are_errors: true
r:
  - release
  - devel
apt_packages:
  - r-cran-rodbc
  - unixodbc-dev
r_github_packages:
  - jimhester/covr
# - hadley/testthat
after_success:
  - Rscript -e 'library(covr);coveralls()'
