# Travis's native R Image (http://docs.travis-ci.com/user/languages/r/)
language: r
sudo: required
warnings_are_errors: true
apt_packages:
 - r-cran-rodbc
r_github_packages:
  - jimhester/covr
  - Rexamine/stringi
  - hadley/httr
after_success:
  - Rscript -e 'library(covr);coveralls()'
